#!/bin/bash
# Automatically generated by monorepo.py

set -e

MONOREPO_ORIGINS="monorepo__dev_proxy monorepo__vw_proxy"

cd target
source ../monorepo.lib.bash
monorepo__initialization main


monorepo__rebase_it "dd791c0" monorepo__vw_proxy        # 2022-01-10T13:30:12-03:00 - Use uhinfra/bullseye:v1.2.0 baseimage.
monorepo__rebase_it "1d81429" monorepo__dev_proxy       # 2022-09-12T11:46:54+02:00 - init
monorepo__rebase_it "f19c564" monorepo__vw_proxy        # 2023-01-26T10:12:24+01:00 - revert to uhinfra base image
monorepo__rebase_it "7c74ab3" monorepo__dev_proxy       # 2023-01-31T11:51:38+01:00 - add oauht.proxy.unhaggle.com configuration block

monorepo__cleanup

